# Generated by Django 4.2.6 on 2023-11-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_shipper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipper',
        ),
    ]
