# Generated by Django 4.2.6 on 2023-11-15 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_shipper'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.shipper'),
        ),
    ]
