# Generated by Django 4.2.6 on 2023-11-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_delivery_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_form',
            new_name='delivery_type',
        ),
    ]
