# Generated by Django 4.2.6 on 2023-11-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_delivery_form_order_delivery_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_type',
            new_name='shipper',
        ),
    ]
