# Generated by Django 4.2.6 on 2023-11-18 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productcategory_alter_shippingaddress_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
