# Generated by Django 4.2.6 on 2023-11-19 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_productcategory_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
