# Generated by Django 4.2.7 on 2023-11-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipcode',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='street',
        ),
    ]
